#!/usr/bin/env python3
"""
build_book.py — assemble SPARK! Lost Signal into one story.md.

Inputs (all in Book3/):
    network.yaml       every page, choice, Mission Log tick and clock cost
    pages.yaml         page numbers, locked once assigned (see below)
    front.md           front matter; {{MISSION_LOG}} expands to the log
    text/*.md          the prose, one section per page:  === A1-OPEN ===
    art_prompts.yaml   style, character sheet, and one scene per page

Outputs:
    story.md           '## Page N' per page, ready for make_epub.py
    art_prompts.json   {"page_001": "<full prompt>", ...} for generate_art.py

Everything a reader is told to *do* (tick a box, cross out a clock box,
turn to a page) is written here from network.yaml, never by hand, so a
page number in the prose can't point to the wrong page.

Page numbers: the first run deals each act's pages into a block, shuffled
within the act so the next page is never simply the next number, and
writes them to pages.yaml. After that they're locked — images are saved
as page_NNN.png, so renumbering would put every picture on the wrong page.
A page added later gets the next free number at the end of the book.

An illustration placeholder is printed under any page whose image isn't
in Book3/art/ yet; once page_NNN.png exists, make_epub.py --art-dir puts
the image there instead.

    python Book3/build_book.py
"""

from __future__ import annotations

import json
import random
import re
import sys
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
ART_DIR = HERE / "art"
SEED = 20261008
ACT_ORDER = (1, 2, 3, 4, 0)


def load_yaml(name: str):
    path = HERE / name
    return yaml.safe_load(path.read_text()) if path.exists() else None


# ── page numbers ───────────────────────────────────────────────────────

def assign_pages(net: dict) -> dict[str, int]:
    path = HERE / "pages.yaml"
    pages: dict[str, int] = load_yaml("pages.yaml") or {}
    missing = [i for i in net["nodes"] if i not in pages]
    if not missing:
        return pages

    if not pages:
        rng = random.Random(SEED)
        n = 1
        for act in ACT_ORDER:
            ids = [i for i, node in net["nodes"].items() if node["act"] == act]
            if net["start"] in ids:
                ids.remove(net["start"])
                pages[net["start"]] = n
                n += 1
            rng.shuffle(ids)
            for i in ids:
                pages[i] = n
                n += 1
    else:
        n = max(pages.values()) + 1
        for i in missing:
            pages[i] = n
            n += 1

    lines = ["# Page numbers — locked. Images are saved as page_NNN.png, so",
             "# changing a number here moves that page's picture too.",
             "# Generated by build_book.py; new pages are appended at the end.", ""]
    for i, p in sorted(pages.items(), key=lambda kv: kv[1]):
        lines.append(f"{i}: {p}")
    path.write_text("\n".join(lines) + "\n")
    print(f"assigned {len(missing)} page number(s) → pages.yaml")
    return pages


# ── prose ──────────────────────────────────────────────────────────────

def load_text() -> dict[str, str]:
    text: dict[str, str] = {}
    for f in sorted((HERE / "text").glob("*.md")):
        parts = re.split(r"(?m)^===\s*([A-Z0-9-]+)\s*===\s*$", f.read_text())
        for k in range(1, len(parts), 2):
            text[parts[k]] = parts[k + 1].strip()
    return text


# ── what the reader is told to do ──────────────────────────────────────

def box(net: dict, flag: str) -> str:
    return f"**{net['flags'][flag].upper()}**"


def clock_name(clock: str) -> str:
    return {"launch": "Launch", "daylight": "Daylight"}[clock]


def condition(net: dict, cond: str) -> str:
    if ">=" in cond:
        clock, n = (x.strip() for x in cond.split(">="))
        n, total = int(n), net["clocks"][clock]["boxes"]
        if n >= total:
            return f"all {total} {clock_name(clock)} boxes are crossed out"
        return f"you've crossed out {n} or more {clock_name(clock)} boxes"
    if cond.startswith("!"):
        return f"you did *not* tick {box(net, cond[1:])}"
    return f"you ticked {box(net, cond)}"


def conditions(net: dict, conds: list[str]) -> str:
    said = [condition(net, c) for c in conds]
    return said[0] if len(said) == 1 else ", ".join(said[:-1]) + ", and " + said[-1]


def log_actions(net: dict, node: dict) -> str:
    acts = []
    for f in node.get("sets", []):
        acts.append(f"tick {box(net, f)}")
    for f in node.get("clears", []):
        acts.append(f"erase {box(net, f)}")
    for clock, n in node.get("cost", {}).items():
        acts.append(f"cross out {n} {clock_name(clock)} box{'es' if n > 1 else ''}")
    if not acts:
        return ""
    return "> ✏️ **Mission Log:** " + "; ".join(acts) + "."


def link(page: int, bold: bool = True) -> str:
    """A page reference that's also a tap target in the EPUB.

    make_epub.py's markdown 'toc' extension gives '## Page 12' the id
    'page-12', so the link lands on the heading.
    """
    text = f"[Page {page}](#page-{page})"
    return f"**{text}**" if bold else text


def ways_on(net: dict, node: dict, pages: dict[str, int]) -> str:
    if "choices" in node:
        return "\n\n".join(f"→ {link(pages[c['to']])} — {c['text']}" for c in node["choices"])
    if "next" in node:
        return f"→ **Turn to {link(pages[node['next']], bold=False)}.**"
    if "route" in node:
        route = node["route"]
        if len(route) == 2:
            return (f"Check your Mission Log. If {conditions(net, route[0]['if'])}, "
                    f"turn to {link(pages[route[0]['to']])}.\n\n"
                    f"Otherwise, turn to {link(pages[route[1]['to']])}.")
        lines = ["Check your Mission Log, and follow the **first** line that's true:", ""]
        for r in route:
            if "if" in r:
                lines.append(f"- If {conditions(net, r['if'])} → {link(pages[r['to']])}")
            else:
                lines.append(f"- Otherwise → {link(pages[r['to']])}")
        return "\n".join(lines)
    ending = node["ending"]
    count = sum(1 for n in net["nodes"].values() if "ending" in n)
    return (f"**THE END**\n\n*{ending['title']}* — one of {count} endings.\n\n"
            f"To fly again, erase your Mission Log and turn to {link(pages[net['start']])}.")


def mission_log(net: dict) -> str:
    rows = ["| ☐ | Box |", "|---|---|"]
    for label in net["flags"].values():
        rows.append(f"| ☐ | {label.upper()} |")
    clocks = []
    for name, c in net["clocks"].items():
        clocks.append(f"**{clock_name(name)}:** " + " ".join(["☐"] * c["boxes"])
                      + f" — each box is {c['each']}. {c['meaning']}")
    return "\n".join(rows) + "\n\n" + "\n\n".join(clocks)


# ── art ────────────────────────────────────────────────────────────────

def full_prompt(art: dict, scene: str) -> str:
    """Style, then the scene, then a description of everyone in it."""
    chars = art["characters"]
    present = [name for name in chars if f"{{{name}}}" in scene]
    for name in present:
        scene = scene.replace(f"{{{name}}}", chars[name]["name"])
    who = " ".join(f"{chars[n]['name']}: {chars[n]['look']}." for n in present)
    return " ".join(x for x in (art["style"].strip(), scene.strip(), who) if x)


def placeholder(art: dict, label: str, scene: str) -> str:
    if (ART_DIR / f"{label}.png").exists():
        return ""
    plain = re.sub(r"\{(\w+)\}", lambda m: art["characters"][m.group(1)]["name"], scene)
    words = plain.split()
    gist = " ".join(words[:28]) + ("…" if len(words) > 28 else "")
    return f"> 🖼️ **Illustration · {label}** — *{gist}*"


# ── main ───────────────────────────────────────────────────────────────

def main() -> int:
    net = load_yaml("network.yaml")
    art = load_yaml("art_prompts.yaml")
    pages = assign_pages(net)
    text = load_text()
    scenes = art["scenes"]

    problems = [f"no prose for {i}" for i in net["nodes"] if i not in text]
    problems += [f"prose for unknown page {i}" for i in text if i not in net["nodes"]]
    problems += [f"no art scene for {i}" for i in net["nodes"] if i not in scenes]
    problems += [f"art scene for unknown page {i}" for i in scenes
                 if i not in net["nodes"] and i != "front"]
    if problems:
        print("\n".join(problems))
        return 1

    front = (HERE / "front.md").read_text().replace("{{MISSION_LOG}}", mission_log(net))
    out = [front.rstrip(), ""]
    prompts = {"front": full_prompt(art, scenes["front"])}
    words = 0
    for nid, page in sorted(pages.items(), key=lambda kv: kv[1]):
        node, label = net["nodes"][nid], f"page_{page:03d}"
        body = text[nid]
        words += len(body.split())
        # A page break before every page, so each one starts a new screen.
        parts = ['<div style="page-break-before: always; break-before: page;"></div>', "",
                 f"## Page {page}", "", f"### {node['title']}", "",
                 placeholder(art, label, scenes[nid]), "", body, "",
                 log_actions(net, node), "", ways_on(net, node, pages), "", "---", ""]
        out.append("\n".join(p for p in parts if p is not None))
        prompts[label] = full_prompt(art, scenes[nid])

    story = re.sub(r"\n{3,}", "\n\n", "\n".join(out))
    (HERE / "story.md").write_text(story)
    (HERE / "art_prompts.json").write_text(json.dumps(prompts, indent=2, ensure_ascii=False) + "\n")
    print(f"story.md: {len(pages)} pages, {words:,} words of prose · "
          f"art_prompts.json: {len(prompts)} prompts")
    return 0


if __name__ == "__main__":
    sys.exit(main())
